services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5000:5432"
    volumes:
      - /home/mav/Documents/db_volumes/patient-service-db:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - internal
    restart: unless-stopped

#    ./mvnw spring-boot:build-image "-Dspring-boot.build-image.imageName=ngdmav/patient-service"
  patient-service:
    image: ngdmav/patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - patient-service-db
    networks:
      - internal
    environment:
      - SPRING_PROFILES_ACTIVE=docker

#    ./mvnw spring-boot:build-image "-Dspring-boot.build-image.imageName=ngdmav/billing-service"
  billing-service:
    image: ngdmav/billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - internal
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker

networks:
  internal:
    driver: bridge