services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5000:5432"
    volumes:
      - /home/mav/Documents/db_volumes/patient-service-db:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - internal
    restart: unless-stopped

#    ./mvnw spring-boot:build-image "-Dspring-boot.build-image.imageName=ngdmav/patient-service"
  patient-service:
    image: ngdmav/patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - patient-service-db
    networks:
      - internal
    environment:
      - SPRING_PROFILES_ACTIVE=docker

#    ./mvnw spring-boot:build-image "-Dspring-boot.build-image.imageName=ngdmav/billing-service"
  billing-service:
    image: ngdmav/billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  internal:
    driver: bridge